# Generated by Django 4.2.4 on 2023-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SALGADOS', 'Salgados'), ('DOCES', 'Doces'), ('BEBIDAS', 'Bebidas')], default='', max_length=100),
        ),
    ]
