# Generated by Django 4.2.3 on 2023-10-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_exibir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='item',
            field=models.ImageField(blank=True, upload_to='itens/%Y/%m/%d/'),
        ),
    ]
