# Generated by Django 4.2.4 on 2023-12-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
